### ISSUE TITLE
Issue with ManyMC

### ISSUE THREAD

**Issue by omerien** [MinecraftMachina/McMouser#8]
(I can't join your Discord server because I have too many servers)
When transitioning from ManyMC to Prism Launcher, please delete also the Meta folder or accept the pull request on the meta repo. It's causing troubles. Thx !

**Comment by ViRb3** [comment]
Removing the meta folder is already written in the migration guide in https://github.com/MinecraftMachina/ManyMC:

> cd ~/Library/Application\ Support
mv ManyMC PrismLauncher
cd PrismLauncher
mv manymc.cfg prismlauncher.cfg
**rm -r meta metacache cache libraries**

The only PR for the meta I can find is https://github.com/MinecraftMachina/meta-multimc-arm64/pull/108, which is irrelevant since ManyMC will no longer get updates, so there's no reason to have an upstream.
